[project]
name = "opl-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker>=40.1.2",
    "fastapi[standard]>=0.128.0",
    "google-auth>=2.0.0",
    "PyJWT>=2.0.0",
    "sqlmodel>=0.0.32",
]
